version: '3.8'

services:
  # Apache Kafka broker
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft (single-node broker+controller)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Листенеры: внешний и внутренний (для контейнеров)
      KAFKA_LISTENERS: "PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # Обязательные dev-настройки для одиночного брокера
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"         # можно оставить так для локалки
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NUM_PARTITIONS: "3"
    volumes:
      - ./docker/kafka:/tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD", "bash", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - microservices

  # HashiCorp Vault для управления секретами
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev
    volumes:
      - ./docker/vault/data:/vault/data
      - ./docker/vault/init.sh:/vault/init.sh
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_SERVER_GRPC_PORT: 8082
      APP_USERS_SERVICE_HOST: users
      APP_USERS_SERVICE_PORT: 8082
    ports:
      - "8081:8082"
    networks:
      - microservices

  users-db:
    image: postgres:17-alpine
    container_name: postgresql-users
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${USERS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./users/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./users/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./users/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${USERS_POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_SERVER_GRPC_PORT: 8082
      APP_DATABASE_HOST: ${USERS_POSTGRES_HOST:-users-db}
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: ${USERS_POSTGRES_DB:-users}
      APP_DATABASE_USER: ${POSTGRES_USER}
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DATABASE_SSLMODE: disable
    depends_on:
      users-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - microservices

  social-db:
    image: postgres:17-alpine
    container_name: postgresql-social
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SOCIAL_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./social/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./social/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./social/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${SOCIAL_POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  social:
    build:
      context: ./social
      dockerfile: Dockerfile
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_SERVER_GRPC_PORT: 8082
      APP_DATABASE_HOST: ${SOCIAL_POSTGRES_HOST}
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: ${SOCIAL_POSTGRES_DB}
      APP_DATABASE_USER: ${POSTGRES_USER}
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DATABASE_SSLMODE: disable
      APP_KAFKA_BROKERS: kafka:29092
      APP_KAFKA_TOPICS_FRIEND_REQUEST_EVENTS: friend-request-events
      APP_USERS_SERVICE_HOST: users
      APP_USERS_SERVICE_PORT: 8082
    depends_on:
      kafka:
        condition: service_healthy
      social-db:
        condition: service_healthy
    ports:
      - "8083:8082"
    networks:
      - microservices

  # PostgreSQL database for chat service
  chat-db:
    image: postgres:17-alpine
    container_name: postgresql-chat
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CHAT_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./chat/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./chat/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./chat/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${CHAT_POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8084:8082"
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_SERVER_GRPC_PORT: 8082
      APP_DATABASE_HOST: ${CHAT_POSTGRES_HOST}
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: ${CHAT_POSTGRES_DB}
      APP_DATABASE_USER: ${POSTGRES_USER}
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DATABASE_SSLMODE: disable
      APP_USERS_SERVICE_HOST: users
      APP_USERS_SERVICE_PORT: 8082
    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - microservices

  # PostgreSQL database for chat service
  notifications-db:
    image: postgres:17-alpine
    container_name: postgresql-notifications
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NOTIFICATIONS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./notifications/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./notifications/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./notifications/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5429:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${NOTIFICATIONS_POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    ports:
      - "8079:8082"
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_DATABASE_HOST: ${NOTIFICATIONS_POSTGRES_HOST}
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: ${NOTIFICATIONS_POSTGRES_DB}
      APP_DATABASE_USER: ${POSTGRES_USER}
      APP_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DATABASE_SSLMODE: disable
      APP_KAFKA_BROKERS: kafka:29092
      APP_KAFKA_TOPICS_FRIEND_REQUEST_EVENTS: friend-request-events
    depends_on:
      kafka:
        condition: service_healthy
      notifications-db:
        condition: service_healthy
    networks:
      - microservices

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      APP_SERVICE_ENVIRONMENT: ${ENVIRONMENT:-dev}
      APP_SERVER_HTTP_PORT: 8080
      APP_SERVER_GRPC_PORT: 8085
      APP_SERVICES_AUTH_HOST: auth
      APP_SERVICES_AUTH_PORT: 8082
      APP_SERVICES_USERS_HOST: users
      APP_SERVICES_USERS_PORT: 8082
      APP_SERVICES_SOCIAL_HOST: social
      APP_SERVICES_SOCIAL_PORT: 8082
      APP_SERVICES_CHAT_HOST: chat
      APP_SERVICES_CHAT_PORT: 8082
    ports:
      - "8080:8080"
      - "8085:8085"
    depends_on:
      - auth
      - users
      - social
      - chat
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
