version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8082"
    networks:
      - microservices

  users-db:
    image: postgres:17-alpine
    container_name: postgresql-users
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${USERS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./users/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./users/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./users/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${USERS_POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${USERS_POSTGRES_HOST}
      DB_PORT: 5434
      DB_NAME: ${USERS_POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSLMODE: disable
    ports:
      - "8082:8082"
    networks:
      - microservices

  social-db:
    image: postgres:17-alpine
    container_name: postgresql-social
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SOCIAL_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./social/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./social/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./social/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${SOCIAL_POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  social:
    build:
      context: ./social
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${SOCIAL_POSTGRES_HOST}
      DB_PORT: 5433
      DB_NAME: ${SOCIAL_POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSLMODE: disable
    depends_on:
      chat-db:
        condition: service_healthy
    ports:
      - "8083:8082"
    networks:
      - microservices

  # PostgreSQL database for chat service
  chat-db:
    image: postgres:17-alpine
    container_name: postgresql-chat
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CHAT_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./chat/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./chat/config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./chat/docker/postgresql/data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${CHAT_POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "8084:8082"
    environment:
      DB_HOST: ${CHAT_POSTGRES_HOST}
      DB_PORT: 5432
      DB_NAME: ${CHAT_POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSLMODE: disable
    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - microservices

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8085:8085"
    depends_on:
      - auth
      - users
      - social
      - chat
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
