service:
  name: gateway
  version: 1.0.0
  environment: dev

server:
  http:
    port: 8080
  grpc:
    port: 8085

auth_service:
  host: auth
  port: 8082

users_service:
  host: users
  port: 8082

social_service:
  host: social
  port: 8082

chat_service:
  host: chat
  port: 8082
