filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - drop_event:
      when:
        not:
          or:
            - equals:
                container.name: orders-management-system-container
            - equals:
                container.name: inventory-service-container

  - decode_json_fields:
      fields: ["ts", "level", "service", "message", "error", "span_id", "trace_id", "component", "operation"]
      target: ""
      overwrite_keys: true

output.logstash:
  hosts: ["graylog:5044"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false